### ISSUE TITLE
Feature Request - Go vet in addition to just lint

### ISSUE THREAD

**Issue by brendanjerwin** [thoughtbot/hound-go#11]
Would it be possible to add Go vet as an option for checks as well as just the lint?

**Comment by bernerdschaefer** [comment]
I think it's best to keep hound focused on style with golint. I talk a bit about why Hound is a great fit for linting here: https://robots.thoughtbot.com/go-hound-and-code-review-comments

In particular, vet deals with program correctness rather than style, and thus is best run before commit and/or on CI. If you're looking for pointers on setting that up, our [Go project template][laces] could be a good place to start.

[laces]: https://github.com/thoughtbot/laces

On a more technical level, it's tricky to include vet in this service, as it's not available as a package.
